add_executable(OLS OLS.cpp)
target_link_libraries(OLS PRIVATE core_lib)
add_executable(OLS_dgels OLS_dgels.cpp)
target_link_libraries(OLS_dgels PRIVATE core_lib)
add_executable(GLS GLS.cpp)
target_link_libraries(GLS PRIVATE core_lib)
add_executable(Image ImageRestoration.cpp)
target_link_libraries(Image PRIVATE core_lib)